# VOLUNTEERS: NAMES AND PROFESSIONS

VOLUNTEER_1 = 'BAR 0525675670'
VOLUNTEER_2 = 'GAL 0525675671'
VOLUNTEER_3 = 'STAV 0525675672'
VOLUNTEER_4 = 'TAL 0525675673'
VOLUNTEER_5 = 'NOAM 0525675674'

PROFESSION_VOLUNTEER_1 = 'FIXING'
PROFESSION_VOLUNTEER_2 = 'CLEANING'
PROFESSION_VOLUNTEER_3 = 'LISTENER'
PROFESSION_VOLUNTEER_4 = 'FOOD'
PROFESSION_VOLUNTEER_5 = 'STUFF'

VOLUNTEER_DICT = {PROFESSION_VOLUNTEER_1: VOLUNTEER_1, PROFESSION_VOLUNTEER_2: VOLUNTEER_2,
                  PROFESSION_VOLUNTEER_3: VOLUNTEER_3,PROFESSION_VOLUNTEER_4:VOLUNTEER_4,
                  PROFESSION_VOLUNTEER_5:VOLUNTEER_5 }

# FIRST REGISTRATION
NAME_SENIOR = input("please enter your name:")
settings = input("Do you have any disabilities?")
PHONE_NUM_SENIOR = int(input("please enter your phone number:"))

# CASE
HELP_KIND_SENIOR = input("please enter your current priority:")
if HELP_KIND_SENIOR in VOLUNTEER_DICT:
    print(VOLUNTEER_DICT[HELP_KIND_SENIOR],". MY PLEASURE. SEE YOU SOON:) ,",VOLUNTEER_DICT[HELP_KIND_SENIOR])
